def default_borehole_layout() -> dict:
    return {
        "schemaVersion": 1,
        "mode": "runtime",
        "regions": {
            "left": ["validation-panel", "ai-workflow"],
            "center": ["log-widget"],
            "right": ["interval-details", "export-panel"],
        },
        "grid": {
            "columns": 12,
            "rowHeight": 72,
            "items": [
                {"widgetId": "total-depth", "x": 0, "y": 0, "w": 2, "h": 1},
                {"widgetId": "interval-count", "x": 2, "y": 0, "w": 2, "h": 1},
                {"widgetId": "curve-count", "x": 4, "y": 0, "w": 2, "h": 1},
                {"widgetId": "corebox-count", "x": 6, "y": 0, "w": 2, "h": 1},
                {"widgetId": "validation-panel", "x": 0, "y": 1, "w": 2, "h": 4},
                {"widgetId": "ai-workflow", "x": 0, "y": 5, "w": 2, "h": 4},
                {"widgetId": "log-widget", "x": 2, "y": 1, "w": 7, "h": 8},
                {"widgetId": "interval-details", "x": 9, "y": 1, "w": 3, "h": 6},
                {"widgetId": "curve-catalog", "x": 9, "y": 7, "w": 3, "h": 3},
                {"widgetId": "export-panel", "x": 9, "y": 10, "w": 3, "h": 3},
                {"widgetId": "data-arrival", "x": 0, "y": 10, "w": 9, "h": 3},
            ],
        },
        "widgets": {
            "total-depth": {
                "type": "singleValue",
                "title": "Total Depth",
                "metric": "total_depth",
                "settings": {"unit": "m"},
            },
            "interval-count": {"type": "singleValue", "title": "Intervals", "metric": "interval_count"},
            "curve-count": {"type": "singleValue", "title": "Curves", "metric": "curve_count"},
            "corebox-count": {"type": "singleValue", "title": "Coreboxes", "metric": "corebox_count"},
            "validation-panel": {"type": "validationPanel", "title": "Validation", "settings": {"maxIssues": 8}},
            "ai-workflow": {"type": "aiWorkflow", "title": "AI Workflow", "settings": {"showSummary": True}},
            "interval-details": {
                "type": "intervalDetails",
                "title": "Depth Metadata",
                "settings": {"editable": True},
            },
            "curve-catalog": {
                "type": "curveCatalog",
                "title": "Curve Catalog",
                "settings": {"showCoverage": True},
            },
            "export-panel": {"type": "exportPanel", "title": "Export", "settings": {"showReadiness": True}},
            "data-arrival": {"type": "dataArrival", "title": "Data Arrival", "settings": {"allowUpload": True}},
            "log-widget": {
                "type": "logWidget",
                "title": "Borehole Log",
                "tracks": [
                    {"id": "depth", "type": "depthAxis", "title": "Depth", "visible": True, "width": 70},
                    {
                        "id": "lithology",
                        "type": "lithology",
                        "title": "Lithology",
                        "visible": True,
                        "width": 180,
                    },
                    {"id": "seam", "type": "seam", "title": "Seam", "visible": True, "width": 90},
                    {
                        "id": "core-images",
                        "type": "images",
                        "title": "Core Images",
                        "visible": True,
                        "width": 120,
                    },
                    {
                        "id": "recovery",
                        "type": "quantitativeBar",
                        "title": "Recovery",
                        "visible": True,
                        "width": 110,
                        "valueField": "recovery_percent",
                        "unit": "%",
                        "min": 0,
                        "max": 100,
                        "color": "#55b7aa",
                    },
                    {
                        "id": "rqd",
                        "type": "quantitativeBar",
                        "title": "RQD",
                        "visible": True,
                        "width": 100,
                        "valueField": "rqd",
                        "unit": "%",
                        "min": 0,
                        "max": 100,
                        "valueMultiplier": 100,
                        "color": "#55b7aa",
                    },
                    {
                        "id": "curves",
                        "type": "curve",
                        "title": "Curves",
                        "visible": True,
                        "width": 260,
                        "curves": [
                            {
                                "curveKey": "gamma",
                                "label": "Gamma",
                                "unit": "API",
                                "color": "#d97706",
                                "visible": True,
                                "scale": {"mode": "manual", "min": 0, "max": 150},
                                "normalization": {"enabled": True, "method": "linear-track-scale"},
                            },
                            {
                                "curveKey": "resistivity",
                                "label": "Resistivity",
                                "unit": "ohm.m",
                                "color": "#2563eb",
                                "visible": True,
                                "scale": {"mode": "manual", "min": 0, "max": 80},
                                "normalization": {"enabled": True, "method": "linear-track-scale"},
                            },
                        ],
                    },
                    {
                        "id": "remarks",
                        "type": "remarks",
                        "title": "Remarks",
                        "visible": True,
                        "width": 220,
                    },
                    {
                        "id": "ai-suggestions",
                        "type": "aiSuggestions",
                        "title": "AI",
                        "visible": True,
                        "width": 120,
                    },
                ],
            }
        },
    }
